apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: ClickHouse
    access: proxy
    isDefault: true
    jsonData:
      port: 8123
      server: clickhouse
      username: default
      protocol: http
